version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres_db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  test_db:
    image: postgres:16
    restart: always
    container_name: postgres_test_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: fastapi_app
    command: bash -c "uvicorn app.server.app:create_app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  postgres_test_data:
